In [1]:
import os
print(os.getcwd())

C:\Users\Rosangela\Documents\datasus_dez_2019\covid_19

In [2]:
import csv
arquivo = open('cnes_ativonone.csv.csv', encoding='utf-8')
leitor = csv.reader(arquivo)
print(next(leitor))

['co_cnes', 'co_ibge', 'no_fantasia', 'ds_tipo_unidade', 'tp_gestao', 'no_logradouro', 'nu_endereco', 'no_bairro', 'co_cep', 'uf', 'municipio', 'nu_telefone']

In [3]:
import pandas as pd
import numpy as np

In [4]:
cnes =pd.read_csv('cnes_ativonone.csv.csv', encoding='utf-8', sep=',', low_memory=False, error_bad_lines=False, 
                  usecols=['co_cnes','co_ibge','ds_tipo_unidade','tp_gestao','uf','municipio'])
cnes.head()

,co_cnes,co_ibge,ds_tipo_unidade,tp_gestao,uf,municipio
0,6577687,292240,CENTRAL DE GESTAO EM SAUDE,M,BA,Mutuípe
1,6578500,500210,CLINICA/CENTRO DE ESPECIALIDADE,M,MS,Bela Vista
2,6577725,355660,CENTRAL DE GESTAO EM SAUDE,M,SP,Vera Cruz
3,6577733,355410,CONSULTORIO ISOLADO,M,SP,Taubaté
4,6577768,410490,UNIDADE DE APOIO DIAGNOSE E TERAPIA (SADT ISOL...,M,PR,Castro

In [5]:
cnes.columns=(['co_cnes', 'co_ibge','descricao', 'tp_gestao', 'uf', 'municipio'])

In [6]:
cnes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 354804 entries, 0 to 354803
Data columns (total 6 columns):
co_cnes      354804 non-null int64
co_ibge      354804 non-null int64
descricao    354804 non-null object
tp_gestao    354804 non-null object
uf           354434 non-null object
municipio    354434 non-null object
dtypes: int64(2), object(4)
memory usage: 16.2+ MB

In [10]:
cod_atividade = pd.read_csv('cod_atividade.csv', sep=',',encoding='Latin-1')
cod_atividade.head()

   cod_unidades                       descricao  total
0             1                  POSTO DE SAUDE  11328
1             2  CENTRO DE SAUDE/UNIDADE BASICA  39253
2             4                     POLICLINICA   8770
3             5                  HOSPITAL GERAL   5795
4             7          HOSPITAL ESPECIALIZADO   1245

In [11]:
cod_atividade.drop(['total'], axis=1)

    cod_unidades                                          descricao
0              1                                     POSTO DE SAUDE
1              2                     CENTRO DE SAUDE/UNIDADE BASICA
2              4                                        POLICLINICA
3              5                                     HOSPITAL GERAL
4              7                             HOSPITAL ESPECIALIZADO
5             15                                      UNIDADE MISTA
6             20                               PRONTO SOCORRO GERAL
7             21                       PRONTO SOCORRO ESPECIALIZADO
8             22                                CONSULTORIO ISOLADO
9             32                              UNIDADE MOVEL FLUVIAL
10            36                    CLINICA/CENTRO DE ESPECIALIDADE
11            39  UNIDADE DE APOIO DIAGNOSE E TERAPIA (SADT ISOL...
12            40                            UNIDADE MOVEL TERRESTRE
13            42  UNIDADE MOVEL DE NIVEL PRE-HOSPITALAR NA AREA ...
14            43                                           FARMACIA
15            50                     UNIDADE DE VIGILANCIA EM SAUDE
16            60  COOPERATIVA OU EMPRESA DE CESSAO DE TRABALHADO...
17            61                   CENTRO DE PARTO NORMAL  ISOLADO
18            62                             HOSPITAL/DIA  ISOLADO
19            67        LABORATORIO CENTRAL DE SAUDE PUBLICA LACEN
20            68                         CENTRAL DE GESTAO EM SAUDE
21            69    CENTRO DE ATENCAO HEMOTERAPIA E OU HEMATOLOGICA
22            70                     CENTRO DE ATENCAO PSICOSSOCIAL
23            71                 CENTRO DE APOIO A SAUDE DA FAMILIA
24            72                UNIDADE DE ATENCAO A SAUDE INDIGENA
25            73                                 PRONTO ATENDIMENTO
26            74                             POLO ACADEMIA DA SAUDE
27            75                                         TELESSAUDE
28            76          CENTRAL DE REGULACAO MEDICA DAS URGENCIAS
29            77   SERVICO DE ATENCAO DOMICILIAR ISOLADO(HOME CARE)
30            78           UNIDADE DE ATENCAO EM REGIME RESIDENCIAL
31            79                                 OFICINA ORTOPEDICA
32            80                       LABORATORIO DE SAUDE PUBLICA
33            81                     CENTRAL DE REGULACAO DO ACESSO
34            82  CENTRAL DE NOTIFICACAO,CAPTACAO E DISTRIB DE O...
35            83  POLO DE PREVENCAO DE DOENCAS E AGRAVOS E PROMO...

In [12]:
cnes['descricao'].value_counts()

CONSULTORIO ISOLADO                                             175140
CLINICA/CENTRO DE ESPECIALIDADE                                  52766
CENTRO DE SAUDE/UNIDADE BASICA                                   38998
UNIDADE DE APOIO DIAGNOSE E TERAPIA (SADT ISOLADO)               27067
POSTO DE SAUDE                                                   11345
POLICLINICA                                                       8457
CENTRAL DE GESTAO EM SAUDE                                        6059
HOSPITAL GERAL                                                    5752
UNIDADE MOVEL DE NIVEL PRE-HOSPITALAR NA AREA DE URGENCIA         4703
FARMACIA                                                          3213
CENTRO DE ATENCAO PSICOSSOCIAL                                    3065
UNIDADE DE VIGILANCIA EM SAUDE                                    3005
POLO ACADEMIA DA SAUDE                                            2523
UNIDADE MOVEL TERRESTRE                                           1460
PRONTO ATENDIMENTO                                                1248
CENTRAL DE REGULACAO DO ACESSO                                    1243
HOSPITAL ESPECIALIZADO                                            1234
CENTRO DE APOIO A SAUDE DA FAMILIA                                1171
UNIDADE DE ATENCAO A SAUDE INDIGENA                               1106
HOSPITAL/DIA - ISOLADO                                             718
UNIDADE MISTA                                                      706
SERVICO DE ATENCAO DOMICILIAR ISOLADO(HOME CARE)                   681
COOPERATIVA OU EMPRESA DE CESSAO DE TRABALHADORES NA SAUDE         633
PRONTO SOCORRO GERAL                                               453
LABORATORIO DE SAUDE PUBLICA                                       417
CENTRO DE ATENCAO HEMOTERAPIA E OU HEMATOLOGICA                    395
POLO DE PREVENCAO DE DOENCAS E AGRAVOS E PROMOCAO DA SAUDE         328
CENTRAL DE REGULACAO MEDICA DAS URGENCIAS                          239
CENTRAL DE REGULACAO DE SERVICOS DE SAUDE                          142
CENTRAL DE NOTIFICACAO,CAPTACAO E DISTRIB DE ORGAOS ESTADUAL       131
PRONTO SOCORRO ESPECIALIZADO                                       129
TELESSAUDE                                                          86
UNIDADE MOVEL FLUVIAL                                               59
LABORATORIO CENTRAL DE SAUDE PUBLICA LACEN                          38
UNIDADE DE ATENCAO EM REGIME RESIDENCIAL                            34
CENTRO DE PARTO NORMAL - ISOLADO                                    33
OFICINA ORTOPEDICA                                                  27
Name: descricao, dtype: int64

In [13]:
cnes[cnes['descricao'] == 'HOSPITAL GERAL']

,co_cnes,co_ibge,descricao,tp_gestao,uf,municipio
33,6578373,150520,HOSPITAL GERAL,D,PA,Oeiras do Pará
608,6592961,210594,HOSPITAL GERAL,E,MA,Lago dos Rodrigues
702,6595197,292740,HOSPITAL GERAL,E,BA,Salvador
792,6597483,410830,HOSPITAL GERAL,M,PR,Foz do Iguaçu
874,6599877,110004,HOSPITAL GERAL,E,RO,Cacoal
894,6600476,290590,HOSPITAL GERAL,E,BA,Campo Alegre de Lourdes
935,6601804,317020,HOSPITAL GERAL,M,MG,Uberlândia
959,6602487,110030,HOSPITAL GERAL,M,RO,Vilhena
984,6603378,353580,HOSPITAL GERAL,M,SP,Paranapanema
1154,6607950,410830,HOSPITAL GERAL,M,PR,Foz do Iguaçu
1530,6618332,355030,HOSPITAL GERAL,M,SP,São Paulo
1780,6625649,351880,HOSPITAL GERAL,M,SP,Guarulhos
1789,6625908,110004,HOSPITAL GERAL,M,RO,Cacoal
2058,6633064,261160,HOSPITAL GERAL,E,PE,Recife
2115,6634540,350760,HOSPITAL GERAL,M,SP,Bragança Paulista
2140,6635148,330630,HOSPITAL GERAL,M,RJ,Volta Redonda
2475,6644996,250690,HOSPITAL GERAL,D,PB,Itabaiana
2484,6645291,430110,HOSPITAL GERAL,E,RS,Arroio dos Ratos
2628,6649270,211130,HOSPITAL GERAL,M,MA,São Luís
2954,6658520,250710,HOSPITAL GERAL,D,PB,Itapororoca
2998,6659772,292530,HOSPITAL GERAL,M,BA,Porto Seguro
3114,6663834,110002,HOSPITAL GERAL,M,RO,Ariquemes
3182,6665322,521930,HOSPITAL GERAL,E,GO,Santa Helena de Goiás
3352,6670385,291733,HOSPITAL GERAL,D,BA,Iuiú
3515,6674585,350950,HOSPITAL GERAL,M,SP,Campinas
3605,6676782,430770,HOSPITAL GERAL,D,RS,Esteio
3685,6679528,251250,HOSPITAL GERAL,D,PB,Queimadas
3697,6679765,430640,HOSPITAL GERAL,E,RS,Dois Irmãos
3718,6680305,420540,HOSPITAL GERAL,M,SC,Florianópolis
3743,6680968,353200,HOSPITAL GERAL,M,SP,Morungaba
...,...,...,...,...,...,...
352886,3344320,291080,HOSPITAL GERAL,M,BA,Feira de Santana
352893,3344614,211130,HOSPITAL GERAL,E,MA,São Luís
352939,3345866,230640,HOSPITAL GERAL,M,CE,Itapipoca
353138,3357783,330455,HOSPITAL GERAL,M,RJ,Rio de Janeiro
353172,3354423,520350,HOSPITAL GERAL,M,GO,Bom Jesus de Goiás
353218,3356027,330630,HOSPITAL GERAL,M,RJ,Volta Redonda
353243,3356868,430510,HOSPITAL GERAL,M,RS,Caxias do Sul
353309,3358860,292265,HOSPITAL GERAL,M,BA,Nordestina
353511,3366219,350280,HOSPITAL GERAL,M,SP,Araçatuba
353537,3366758,292740,HOSPITAL GERAL,M,BA,Salvador
353559,3367371,355030,HOSPITAL GERAL,M,SP,São Paulo
353620,3369293,260120,HOSPITAL GERAL,D,PE,Arcoverde
353719,3371980,410690,HOSPITAL GERAL,M,PR,Curitiba
353746,3373398,420540,HOSPITAL GERAL,M,SC,Florianópolis
353785,3374548,420540,HOSPITAL GERAL,M,SC,Florianópolis
353786,3374599,261160,HOSPITAL GERAL,E,PE,Recife
353921,3378330,330455,HOSPITAL GERAL,M,RJ,Rio de Janeiro
353936,3378691,430580,HOSPITAL GERAL,D,RS,Constantina
353998,3381412,291080,HOSPITAL GERAL,M,BA,Feira de Santana
354141,3384993,230480,HOSPITAL GERAL,M,CE,Granjeiro
354146,3385205,170070,HOSPITAL GERAL,E,TO,Alvorada
354171,3386023,210130,HOSPITAL GERAL,M,MA,Bacuri
354241,3388301,210300,HOSPITAL GERAL,M,MA,Caxias
354459,3394514,230440,HOSPITAL GERAL,M,CE,Fortaleza
354519,3398315,250750,HOSPITAL GERAL,M,PB,João Pessoa
354557,3401146,230580,HOSPITAL GERAL,M,CE,Ipu
354563,3400573,520870,HOSPITAL GERAL,M,GO,Goiânia
354607,3401928,291080,HOSPITAL GERAL,M,BA,Feira de Santana
354716,3405702,320520,HOSPITAL GERAL,E,ES,Vila Velha
354728,3407829,290200,HOSPITAL GERAL,E,BA,Aracatu

In [17]:
type('co_cnes')

str

In [20]:
cnes['co_cnes'].duplicated(keep=False).value_counts()

False    354804
Name: co_cnes, dtype: int64

In [14]:
cnes['co_cnes'].count()

354804

In [23]:
rede_ab = cnes[cnes['descricao'] == 'CENTRO DE SAUDE/UNIDADE BASICA']
rede_ab.groupby('descricao')['uf'].value_counts(ascending=False)

descricao                       uf
CENTRO DE SAUDE/UNIDADE BASICA  MG    5213
                                SP    5073
                                BA    3584
                                PE    2361
                                RS    2050
                                CE    2040
                                PR    1967
                                RJ    1886
                                MA    1848
                                SC    1623
                                PB    1424
                                GO    1344
                                PA    1263
                                PI    1011
                                RN     904
                                AL     857
                                MT     824
                                ES     779
                                MS     624
                                AM     558
                                SE     469
                                TO     401
                                RO     257
                                AC     230
                                DF     191
                                RR     109
                                AP     107
Name: uf, dtype: int64

In [24]:
rede_ab1 = cnes[cnes['descricao'] == 'POSTO DE SAUDE']
rede_ab1.groupby('descricao')['uf'].value_counts(ascending=False)

descricao       uf
POSTO DE SAUDE  BA    1237
                MG    1124
                PR     994
                PA     970
                RS     818
                MA     649
                PI     574
                CE     561
                RJ     518
                RN     444
                PE     415
                SC     402
                SP     400
                PB     331
                SE     297
                AL     243
                MT     242
                ES     229
                GO     204
                AM     175
                RO     157
                AP     119
                AC      77
                RR      77
                MS      49
                TO      37
                DF       2
Name: uf, dtype: int64

#### Separando pela rede de atendimento existente para Covid-19, sem os hospitais de campanha e sem os leitos da saúde privada

In [25]:
hospital = cnes[cnes['descricao'] == 'HOSPITAL GERAL']
hospital.groupby('descricao')['uf'].value_counts(ascending=False)

descricao       uf
HOSPITAL GERAL  SP    849
                MG    585
                BA    499
                PR    459
                RJ    396
                GO    363
                RS    328
                MA    246
                CE    241
                PA    234
                PE    231
                SC    220
                MT    168
                PB    132
                MS    115
                PI    108
                ES    104
                AM     88
                RO     83
                RN     80
                TO     65
                AL     50
                SE     36
                DF     35
                AC     16
                RR     11
                AP     10
Name: uf, dtype: int64

In [28]:
pa = cnes[cnes['descricao'] == 'PRONTO ATENDIMENTO']
pa.groupby('descricao')['uf'].value_counts(ascending=False)

descricao           uf
PRONTO ATENDIMENTO  SP    311
                    RJ    118
                    MG    112
                    PR     94
                    BA     89
                    RS     88
                    SC     52
                    CE     45
                    PE     42
                    MT     38
                    ES     36
                    PA     31
                    GO     30
                    PB     26
                    TO     20
                    MA     19
                    MS     19
                    RN     18
                    AL     15
                    AM     11
                    DF     10
                    PI      7
                    SE      6
                    RO      5
                    AC      4
                    AP      1
                    RR      1
Name: uf, dtype: int64

In [29]:
ps = cnes[cnes['descricao'] == 'PRONTO SOCORRO GERAL']
ps.groupby('descricao')['uf'].value_counts(ascending=False)

descricao             uf
PRONTO SOCORRO GERAL  SP    171
                      MG     59
                      RJ     53
                      PR     22
                      RS     22
                      GO     16
                      BA     12
                      MT     12
                      MA      9
                      SC      9
                      PA      8
                      RN      8
                      SE      8
                      PE      7
                      AL      6
                      ES      6
                      MS      6
                      PI      6
                      PB      4
                      CE      3
                      DF      2
                      AP      1
                      RO      1
                      TO      1
Name: uf, dtype: int64

In [31]:
samu = cnes[cnes['descricao'] == 'UNIDADE MOVEL DE NIVEL PRE-HOSPITALAR NA AREA DE URGENCIA']
samu.groupby('descricao')['uf'].value_counts(ascending=False)

descricao                                                  uf
UNIDADE MOVEL DE NIVEL PRE-HOSPITALAR NA AREA DE URGENCIA  SP    989
                                                           BA    422
                                                           MG    411
                                                           PR    287
                                                           RS    275
                                                           RJ    239
                                                           GO    215
                                                           PE    215
                                                           PB    207
                                                           SC    167
                                                           MA    145
                                                           CE    142
                                                           PA    136
                                                           PI    129
                                                           AM    115
                                                           SE     88
                                                           DF     87
                                                           AL     81
                                                           RN     69
                                                           MT     61
                                                           AC     51
                                                           MS     47
                                                           ES     39
                                                           RO     27
                                                           RR     23
                                                           TO     21
                                                           AP     15
Name: uf, dtype: int64

In [32]:
brasil = pd.read_csv('brazil-population-1998-2017.csv', sep=';', encoding='utf8')
brasil.head()

,code,city,state,abbreviation,region,lat,long,year,population
0,110001,Alta Floresta D'Oeste,Rondônia,RO,NORTE,-11.9283,-61.9953,2014,25652
1,110001,Alta Floresta D'Oeste,Rondônia,RO,NORTE,-11.9283,-61.9953,2015,25578
2,110001,Alta Floresta D'Oeste,Rondônia,RO,NORTE,-11.9283,-61.9953,2011,24228
3,110001,Alta Floresta D'Oeste,Rondônia,RO,NORTE,-11.9283,-61.9953,2009,24354
4,110001,Alta Floresta D'Oeste,Rondônia,RO,NORTE,-11.9283,-61.9953,2006,29005

In [33]:
brasil17 = brasil[brasil['year'] == 2017]
brasil17.head()

,code,city,state,abbreviation,region,lat,long,year,population
15,110001,Alta Floresta D'Oeste,Rondônia,RO,NORTE,-11.92830,-61.9953,2017,25437
36,110002,Ariquemes,Rondônia,RO,NORTE,-9.90571,-63.0325,2017,107345
48,110003,Cabixi,Rondônia,RO,NORTE,-13.49450,-60.5520,2017,6224
76,110004,Cacoal,Rondônia,RO,NORTE,-11.43430,-61.4562,2017,88507
89,110005,Cerejeiras,Rondônia,RO,NORTE,-13.18700,-60.8168,2017,17934

In [34]:
brasil17.rename(columns={'code': 'co_ibge'}, inplace=True)
brasil17.head()

C:\Users\Rosangela\Anaconda3\lib\site-packages\pandas\core\frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

,co_ibge,city,state,abbreviation,region,lat,long,year,population
15,110001,Alta Floresta D'Oeste,Rondônia,RO,NORTE,-11.92830,-61.9953,2017,25437
36,110002,Ariquemes,Rondônia,RO,NORTE,-9.90571,-63.0325,2017,107345
48,110003,Cabixi,Rondônia,RO,NORTE,-13.49450,-60.5520,2017,6224
76,110004,Cacoal,Rondônia,RO,NORTE,-11.43430,-61.4562,2017,88507
89,110005,Cerejeiras,Rondônia,RO,NORTE,-13.18700,-60.8168,2017,17934

In [35]:
brasil17.drop(['state','abbreviation','lat','long','year', 'population'], axis=1).head()

    co_ibge                   city region
15   110001  Alta Floresta D'Oeste  NORTE
36   110002              Ariquemes  NORTE
48   110003                 Cabixi  NORTE
76   110004                 Cacoal  NORTE
89   110005             Cerejeiras  NORTE

In [44]:
df = cnes.join(brasil17.set_index('co_ibge'), on='co_ibge')

In [45]:
df.head()

,co_cnes,co_ibge,descricao,tp_gestao,uf,municipio,city,state,abbreviation,region,lat,long,year,population
0,6577687,292240,CENTRAL DE GESTAO EM SAUDE,M,BA,Mutuípe,Mutuípe,Bahia,BA,NORDESTE,-13.2284,-39.5044,2017.0,22998.0
1,6578500,500210,CLINICA/CENTRO DE ESPECIALIDADE,M,MS,Bela Vista,Bela Vista,Mato Grosso do Sul,MS,CENTRO OESTE,-22.1073,-56.5263,2017.0,24331.0
2,6577725,355660,CENTRAL DE GESTAO EM SAUDE,M,SP,Vera Cruz,Vera Cruz,São Paulo,SP,SUDESTE,-22.2183,-49.8207,2017.0,10963.0
3,6577733,355410,CONSULTORIO ISOLADO,M,SP,Taubaté,Taubaté,São Paulo,SP,SUDESTE,-23.0104,-45.5593,2017.0,307953.0
4,6577768,410490,UNIDADE DE APOIO DIAGNOSE E TERAPIA (SADT ISOL...,M,PR,Castro,Castro,Paraná,PR,SUL,-24.7891,-50.0108,2017.0,71501.0

In [46]:
df.drop(['municipio', 'abbreviation', 'year', 'population'], axis=1, inplace=True)

In [47]:
df.head(2)

,co_cnes,co_ibge,descricao,tp_gestao,uf,city,state,region,lat,long
0,6577687,292240,CENTRAL DE GESTAO EM SAUDE,M,BA,Mutuípe,Bahia,NORDESTE,-13.2284,-39.5044
1,6578500,500210,CLINICA/CENTRO DE ESPECIALIDADE,M,MS,Bela Vista,Mato Grosso do Sul,CENTRO OESTE,-22.1073,-56.5263

In [49]:
hg = df[df['descricao'] == 'HOSPITAL GERAL']

In [50]:
hg.head()

,co_cnes,co_ibge,descricao,tp_gestao,uf,city,state,region,lat,long
33,6578373,150520,HOSPITAL GERAL,D,PA,Oeiras do Pará,Pará,NORTE,-2.00358,-49.8628
608,6592961,210594,HOSPITAL GERAL,E,MA,Lago dos Rodrigues,Maranhão,NORDESTE,-4.61173,-44.9798
702,6595197,292740,HOSPITAL GERAL,E,BA,Salvador,Bahia,NORDESTE,-12.97180,-38.5011
792,6597483,410830,HOSPITAL GERAL,M,PR,Foz do Iguaçu,Paraná,SUL,-25.54270,-54.5827
874,6599877,110004,HOSPITAL GERAL,E,RO,Cacoal,Rondônia,NORTE,-11.43430,-61.4562

In [59]:
hg.to_csv('hospital_estado_csv')

In [60]:
df.groupby('descricao')['region'].value_counts()

descricao                                                     region
CENTRAL DE GESTAO EM SAUDE                                    NORDESTE        1946
                                                              SUDESTE         1785
                                                              SUL             1312
                                                              CENTRO OESTE     524
                                                              NORTE            492
CENTRAL DE NOTIFICACAO,CAPTACAO E DISTRIB DE ORGAOS ESTADUAL  NORDESTE          42
                                                              SUDESTE           40
                                                              SUL               24
                                                              NORTE             14
                                                              CENTRO OESTE      11
CENTRAL DE REGULACAO DE SERVICOS DE SAUDE                     NORDESTE          99
                                                              SUDESTE           26
                                                              NORTE              8
                                                              CENTRO OESTE       6
                                                              SUL                3
CENTRAL DE REGULACAO DO ACESSO                                SUDESTE          347
                                                              NORDESTE         300
                                                              SUL              246
                                                              CENTRO OESTE     221
                                                              NORTE            129
CENTRAL DE REGULACAO MEDICA DAS URGENCIAS                     SUDESTE           90
                                                              NORDESTE          63
                                                              NORTE             30
                                                              CENTRO OESTE      28
                                                              SUL               28
CENTRO DE APOIO A SAUDE DA FAMILIA                            NORDESTE         748
                                                              SUDESTE          132
                                                              SUL              118
                                                              NORTE            103
                                                              CENTRO OESTE      70
                                                                              ...
UNIDADE DE ATENCAO A SAUDE INDIGENA                           CENTRO OESTE     196
                                                              NORDESTE         172
                                                              SUDESTE           37
                                                              SUL               34
UNIDADE DE ATENCAO EM REGIME RESIDENCIAL                      SUDESTE           22
                                                              SUL                8
                                                              NORDESTE           4
UNIDADE DE VIGILANCIA EM SAUDE                                NORDESTE        1022
                                                              SUDESTE          981
                                                              NORTE            527
                                                              CENTRO OESTE     279
                                                              SUL              196
UNIDADE MISTA                                                 NORDESTE         486
                                                              NORTE             88
                                                              SUDESTE           69
                                                              SUL               35
                                                              CENTRO OESTE      28
UNIDADE MOVEL DE NIVEL PRE-HOSPITALAR NA AREA DE URGENCIA     SUDESTE         1678
                                                              NORDESTE        1498
                                                              SUL              729
                                                              CENTRO OESTE     410
                                                              NORTE            388
UNIDADE MOVEL FLUVIAL                                         NORTE             55
                                                              CENTRO OESTE       2
                                                              SUL                2
UNIDADE MOVEL TERRESTRE                                       SUDESTE          460
                                                              NORDESTE         425
                                                              SUL              247
                                                              NORTE            169
                                                              CENTRO OESTE     158
Name: region, Length: 180, dtype: int64

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 354804 entries, 0 to 354803
Data columns (total 8 columns):
co_cnes      354804 non-null int64
co_ibge      354804 non-null int64
descricao    354804 non-null object
tp_gestao    354804 non-null object
uf           354434 non-null object
city         354434 non-null object
state        354434 non-null object
region       354434 non-null object
dtypes: int64(2), object(6)
memory usage: 21.7+ MB

In [61]:
df['tp_gestao'].value_counts()

M    331709
E     16612
D      6381
S       102
Name: tp_gestao, dtype: int64